version: "3"

services:
  app:
    image: golang:1.8
    volumes:
      - .:/go/src/notes
    working_dir: /go/src/notes
    command: bash -c "go get . && go run cmd/main.go"
    environment:
      - DB_URL=db:27017
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mongo

  test:
    image: golang:1.8
    volumes:
      - .:/go/src/notes
    working_dir: /go/src/notes
    command: bash -c "go get . && go test"
    depends_on:
      - db
